/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GetAQuoteRouteImport } from './routes/get-a-quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAutoRouteImport } from './routes/services.auto'
import { Route as ServicesBusinessRouteImport } from './routes/services.business'
import { Route as ServicesHomeRouteImport } from './routes/services.home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAQuoteRoute = GetAQuoteRouteImport.update({
  id: '/get-a-quote',
  path: '/get-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAutoRoute = ServicesAutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBusinessRoute = ServicesBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHomeRoute = ServicesHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/auto': typeof ServicesAutoRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/home': typeof ServicesHomeRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/services/auto': typeof ServicesAutoRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/home': typeof ServicesHomeRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/auto': typeof ServicesAutoRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/home': typeof ServicesHomeRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/get-a-quote'
    | '/services'
    | '/services/auto'
    | '/services/business'
    | '/services/home'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/get-a-quote'
    | '/services/auto'
    | '/services/business'
    | '/services/home'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/get-a-quote'
    | '/services'
    | '/services/auto'
    | '/services/business'
    | '/services/home'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GetAQuoteRoute: typeof GetAQuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-quote': {
      id: '/get-a-quote'
      path: '/get-a-quote'
      fullPath: '/get-a-quote'
      preLoaderRoute: typeof GetAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/auto': {
      id: '/services/auto'
      path: '/auto'
      fullPath: '/services/auto'
      preLoaderRoute: typeof ServicesAutoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/business': {
      id: '/services/business'
      path: '/business'
      fullPath: '/services/business'
      preLoaderRoute: typeof ServicesBusinessRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/home': {
      id: '/services/home'
      path: '/home'
      fullPath: '/services/home'
      preLoaderRoute: typeof ServicesHomeRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAutoRoute: typeof ServicesAutoRoute
  ServicesBusinessRoute: typeof ServicesBusinessRoute
  ServicesHomeRoute: typeof ServicesHomeRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAutoRoute: ServicesAutoRoute,
  ServicesBusinessRoute: ServicesBusinessRoute,
  ServicesHomeRoute: ServicesHomeRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GetAQuoteRoute: GetAQuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
